server:
  port: 8083

#键值对配置
name: zhangsan

#对象的配置
person:
  name: zhangsan
  age: 18
  addr: beijing

#行内对象配置
#person: {name: zhangsna,age: 18,addr: beijing}

#配置数组、集合(普通字符串)
city:
  - beijing
  - tianjin
  - xian

#配置数组、集合(对象数据)
student:
  - name: zhang
    age: 18
    addr: beijing
  - name: li
    age: 17
    addr: tianjin

#Map配置
map:
  key1: value1
  key2: value2